### ISSUE TITLE
友链 | fa_555's blog

### ISSUE THREAD

**Issue by FA555** [FA555/fa555.github.io#18]
https://fa555.github.io/links/ 

 友链

**Comment by StudyingFather** [comment]
神仙求换个 [友链](https://studyingfather.com) QwQ

**Comment by oierwyh** [comment]
神仙求换个 [友链](https://www.cnblogs.com/oierwyh/) QwQ

**Comment by FA555** [comment]
@oierwyh @StudyingFather 已经添加辣 ![/kel](https://fa555.github.io/files/kel.png)

**Comment by FA555** [comment]
如果有 id 不合适的请在这里留言，不好意思了

话说这个格式是不是有点单调，应该加个头像图片啥的![/yiw](https://fa555.github.io/files/a.jpg)

**Comment by is-zxy** [comment]
神仙求换个[友链](http://zxyer.xyz/)QwQ

**Comment by FA555** [comment]
> @is-zxy
> 神仙求换个[友链](http://zxyer.xyz/)QwQ

已经添加啦 /qiang

**Comment by ghost** [comment]
神仙求互换友链QwQ 
[link](https://userunknownx.github.io/)

同时问一下您的头像需要用哪一个QvQ，麻烦给下链接，不要用洛谷的QwQ

**Comment by FA555** [comment]
> @UserUnknownX
> 神仙求互换友链QwQ 
> [link](https://userunknownx.github.io/)
> 
> 同时问一下您的头像需要用哪一个QvQ，麻烦给下链接，不要用洛谷的QwQ

已经加了已经加了（

前两天开学在搞文化课没看到，不好意思（

头像用 QQ(591752976) 头像就好吧 qaq

**Comment by ghost** [comment]
添加完毕QwQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FA555"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 晚上9:36
收件人:&nbsp;"FA555/fa555.github.io"<fa555.github.io@noreply.github.com&gt;;
抄送:&nbsp;"UserUnknown"<userunknownx@protonmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FA555/fa555.github.io] 友链 | fa_555's blog (#18)





  
@UserUnknownX
 神仙求互换友链QwQ
 link
 
同时问一下您的头像需要用哪一个QvQ，麻烦给下链接，不要用洛谷的QwQ
  
已经加了已经加了（
 
前两天开学在搞文化课没看到，不好意思（
 
头像用 QQ(591752976) 头像就好吧 qaq

**Comment by ghost** [comment]
> @FA555
> > @UserUnknownX
> > 神仙求互换友链QwQ 
> > [link](https://userunknownx.github.io/)
> > 
> > 同时问一下您的头像需要用哪一个QvQ，麻烦给下链接，不要用洛谷的QwQ
> 
> 已经加了已经加了（
> 
> 前两天开学在搞文化课没看到，不好意思（
> 
> 头像用 QQ(591752976) 头像就好吧 qaq

求更改下友链qaq

麻烦改为

`NekoX | https://nekox.cn`
